name: verl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - comm=0.2.3
  - curl=8.17.0
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.1
  - graalpy=23.0.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libcurl=8.17.0
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnghttp2=1.67.0
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - patch=2.8
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - prompt-toolkit=3.0.52
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.8
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - airportsdata==20250909
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - apache-tvm-ffi==0.1.0b15
      - apex==0.1
      - astor==0.8.1
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==16.0.1
      - blake3==1.0.8
      - cachetools==6.2.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - click==8.2.1
      - cloudpickle==3.1.1
      - cmake==4.1.0
      - codetiming==1.4.0
      - colorful==0.5.7
      - compressed-tensors==0.9.3
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.1
      - cuda-python==13.0.3
      - cupy-cuda12x==13.6.0
      - datasets==4.2.0
      - decord==0.6.0
      - deprecated==1.2.18
      - depyf==0.18.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - fastapi==0.119.1
      - fastapi-cli==0.0.14
      - fastapi-cloud-cli==0.3.1
      - fastrlock==0.8.3
      - fastuuid==0.14.0
      - filelock==3.20.0
      - flash-attn==2.7.4.post1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.27.0
      - google-auth==2.41.1
      - googleapis-common-protos==1.71.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - identify==2.6.15
      - idna==3.11
      - importlib-metadata==8.0.0
      - iniconfig==2.3.0
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.11.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lark==1.2.2
      - liger-kernel==0.6.2
      - litellm==1.78.7
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.12
      - loguru==0.7.3
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mathruler==0.1.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - modelscope==1.31.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.19.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - nanobind==2.9.2
      - networkx==3.4.2
      - ninja==1.13.0
      - nodeenv==1.9.1
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cudnn-frontend==1.15.0
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-cutlass-dsl==4.2.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - openai==2.6.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-fixer==0.2.5
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-exporter-prometheus==0.59b0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.13
      - optree==0.17.0
      - orjson==3.11.3
      - outlines==0.1.11
      - outlines-core==0.1.26
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post6
      - peft==0.17.1
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==4.25.8
      - psutil==7.1.1
      - py-cpuinfo==9.0.0
      - py-spy==0.4.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-extra-types==2.10.6
      - pyext==0.7
      - pylatexenc==2.10
      - pynvml==13.0.1
      - pytest==8.4.2
      - python-dotenv==1.1.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyvers==0.1.0
      - pyyaml==6.0.3
      - qwen-vl-utils==0.0.14
      - ray==2.50.1
      - referencing==0.37.0
      - regex==2025.10.23
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.1
      - rpds-py==0.28.0
      - rsa==4.9.1
      - ruff==0.14.1
      - safetensors==0.6.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.42.1
      - setproctitle==1.3.7
      - setuptools-scm==9.2.2
      - sgl-kernel==0.1.0
      - sglang==0.4.6.post1
      - shellingham==1.5.4
      - smart-open==7.4.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - starlette==0.48.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensordict==0.10.0
      - tiktoken==0.12.0
      - tokenizers==0.21.4
      - tomli==2.3.0
      - torch==2.6.0+cu126
      - torch-memory-saver==0.0.9
      - torchao==0.14.0
      - torchaudio==2.6.0+cu126
      - torchdata==0.11.0
      - torchvision==0.21.0+cu126
      - tqdm==4.67.1
      - transformers==4.51.1
      - triton==3.2.0
      - typer==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - verl==0.7.0.dev0
      - virtualenv==20.35.3
      - wandb==0.22.2
      - watchfiles==1.1.1
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - xgrammar==0.1.18
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/haskari/miniconda3/envs/verl
